title: FCards
description: Learning F# through card games

baseurl: /FCards

collections:
  chapters:
    output: true
    permalink: :collection/:name

relative_links:
  enabled:     true
  collections: true